CREATE TABLE NGUOIDUNG (
    UserID VARCHAR(10) PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(50) NOT NULL,
    TrinhDo VARCHAR(2) NOT NULL CHECK (TrinhDo IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    MucTieuK SMALLINT NOT NULL CHECK (MucTieuK >= 0),
    MucTieuTV SMALLINT NOT NULL CHECK (MucTieuTV >= 0),
    NgayTaoTK DATE NOT NULL DEFAULT CURRENT_DATE,
    VaiTro SMALLINT NOT NULL CHECK (VaiTro IN (0, 1)),
    LanTruyCapCuoi TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_muctieu_soluong CHECK (VaiTro = 0 OR (MucTieuK > 0 OR MucTieuTV > 0))
);

CREATE TABLE BAIHOC (
    BaiHocID VARCHAR(10) PRIMARY KEY,
    TenBai VARCHAR(100) NOT NULL,
    Loai VARCHAR(10) NOT NULL CHECK (Loai IN ('TuVung', 'Kanji')),
    TrinhDo VARCHAR(2) NOT NULL CHECK (TrinhDo IN ('N5', 'N4', 'N3', 'N2', 'N1'))
);

CREATE TABLE AUDIO (
    AudioID VARCHAR(10) PRIMARY KEY,
    Audio TEXT NOT NULL CHECK (Audio ~* '^https?://')
);

CREATE TABLE KANJI (
    KanjiID VARCHAR(10) PRIMARY KEY,
    KyTu CHAR(1) NOT NULL,
    BaiHocID VARCHAR(10) NOT NULL REFERENCES BAIHOC(BaiHocID),
    Nghia TEXT NOT NULL,
    TrinhDo VARCHAR(2) NOT NULL CHECK (TrinhDo IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    SoNet SMALLINT NOT NULL CHECK (SoNet > 0),
    Image TEXT NOT NULL CHECK (Image ~* '^https?://')
);

CREATE TABLE CACHDOCKANJI (
    CachDocID VARCHAR(10) PRIMARY KEY,
    KanjiID VARCHAR(10) NOT NULL REFERENCES KANJI(KanjiID),
    CachDoc VARCHAR(50) NOT NULL,
    Loai VARCHAR(10) NOT NULL CHECK (Loai IN ('Onyomi', 'Kunyomi')),
    DoPhoBien BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE TUVUNG (
    TuVungID VARCHAR(10) PRIMARY KEY,
    TuVung VARCHAR(50) NOT NULL,
    CachDoc VARCHAR(100) NOT NULL,
    Nghia TEXT NOT NULL,
    BaiHocID VARCHAR(10) NOT NULL REFERENCES BAIHOC(BaiHocID),
    ViDuJan TEXT NOT NULL,
    TrinhDo VARCHAR(2) NOT NULL CHECK (TrinhDo IN ('N5', 'N4', 'N3', 'N2', 'N1')),
    ViDuViet TEXT NOT NULL,
    AudioID VARCHAR(10) NOT NULL REFERENCES AUDIO(AudioID)
);

CREATE TABLE TUVUNGKANJI (
    TuVungID VARCHAR(10) NOT NULL REFERENCES TUVUNG(TuVungID),
    KanjiID VARCHAR(10) NOT NULL REFERENCES KANJI(KanjiID),
    MoTa TEXT,
    PRIMARY KEY (TuVungID, KanjiID)
);

CREATE TABLE BAITAPONTAP (
    BTOntapID VARCHAR(10) PRIMARY KEY,
    TenBaiTap VARCHAR(100) NOT NULL,
    BaiHocID VARCHAR(10) NOT NULL REFERENCES BAIHOC(BaiHocID)
);

CREATE TABLE CAUHOI (
    CauHoiID VARCHAR(10) PRIMARY KEY,
    NoiDung TEXT NOT NULL,
    BTOnTapID VARCHAR(10) NOT NULL REFERENCES BAITAPONTAP(BTOntapID)
);

CREATE TABLE CACLUACHON (
    LuaChonID VARCHAR(10) PRIMARY KEY,
    NoiDung TEXT NOT NULL,
    CauHoiID VARCHAR(10) NOT NULL REFERENCES CAUHOI(CauHoiID),
    DapAnDung BOOLEAN NOT NULL
);

CREATE TABLE TRANGTHAIKANJI (
    UserID VARCHAR(10) NOT NULL REFERENCES NGUOIDUNG(UserID),
    KanjiID VARCHAR(10) NOT NULL REFERENCES KANJI(KanjiID),
    NgayHocLanGanNhat TIMESTAMPTZ,
    GhiChu TEXT,
    TrangThai SMALLINT NOT NULL DEFAULT 0 CHECK (TrangThai IN (0, 1, 2)),
    PRIMARY KEY (UserID, KanjiID)
);

CREATE TABLE TRANGTHAITUVUNG (
    UserID VARCHAR(10) NOT NULL REFERENCES NGUOIDUNG(UserID),
    TuVungID VARCHAR(10) NOT NULL REFERENCES TUVUNG(TuVungID),
    NgayHocLanGanNhat TIMESTAMPTZ,
    GhiChu TEXT,
    TrangThai SMALLINT NOT NULL DEFAULT 0 CHECK (TrangThai IN (0, 1, 2)),
    PRIMARY KEY (UserID, TuVungID)
);

CREATE TABLE NHATKYLAMBAI (
    LamBaiID SERIAL PRIMARY KEY,
    NgayLam TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID VARCHAR(10) NOT NULL REFERENCES NGUOIDUNG(UserID),
    BTOntapID VARCHAR(10) NOT NULL REFERENCES BAITAPONTAP(BTOntapID),
    SoLanLamBai SMALLINT NOT NULL CHECK (SoLanLamBai > 0),
    Diem NUMERIC(3,1) NOT NULL CHECK (Diem >= 0 AND Diem <= 10.0)
);

CREATE TABLE CHITIETLAMBAI (
    CTLamBaiID SERIAL PRIMARY KEY,
    LamBaiID INT NOT NULL REFERENCES NHATKYLAMBAI(LamBaiID),
    CauHoiID VARCHAR(10) NOT NULL REFERENCES CAUHOI(CauHoiID),
    LuaChonID VARCHAR(10) NOT NULL REFERENCES CACLUACHON(LuaChonID),
    LaDung BOOLEAN NOT NULL
);

CREATE TABLE TIENDOHANGNGAY (
    TienDoID VARCHAR(10) PRIMARY KEY,
    NgayHoc DATE NOT NULL DEFAULT CURRENT_DATE,
    UserID VARCHAR(10) NOT NULL REFERENCES NGUOIDUNG(UserID),
    SoLuongTuVungDaHoc SMALLINT NOT NULL DEFAULT 0 CHECK (SoLuongTuVungDaHoc >= 0),
    SoLuongKanjiDaHoc SMALLINT NOT NULL DEFAULT 0 CHECK (SoLuongKanjiDaHoc >= 0),
    TrangThai BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TIENDOHANGNGAYCHITIET (
    ChiTietID VARCHAR(10) PRIMARY KEY,
    TienDoID VARCHAR(10) NOT NULL REFERENCES TIENDOHANGNGAY(TienDoID),
    KanjiID VARCHAR(10) REFERENCES KANJI(KanjiID),
    TuVungID VARCHAR(10) REFERENCES TUVUNG(TuVungID),
    CONSTRAINT chk_not_both_null CHECK (KanjiID IS NOT NULL OR TuVungID IS NOT NULL)
);

ALTER TABLE public.TIENDOHANGNGAYCHITIET 
ADD CONSTRAINT chong_trung_chitiet_kanji UNIQUE (TienDoID, KanjiID);

ALTER TABLE public.TIENDOHANGNGAYCHITIET 
ADD CONSTRAINT chong_trung_chitiet_tuvung UNIQUE (TienDoID, TuVungID);

